language: node_js
node_js:
  - '9'
  - '8'
  - '7'
  - '6'
os:
  - linux
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
  directories:
  - "~/.npm"
notifications:
  email: false
script:
  - yarn test:ci
jobs:
  include:
    - stage: NPM Vet
      node_js: "8"
      before_script:
        - yarn global add npmvet
      script: yarn verify:npmvet
    - stage: Node Security
      node_js: "8"
      before_script:
        - yarn global add nsp
      script: yarn verify:nsp
    - stage: Code Coverage
      node_js: "8"
      script: yarn test:coverage:ci
      after_success:
        - cat ./coverage/lcov.info | coveralls
    - stage: Build and deploy
      node_js: "8"
      before_script:
        - yarn global add greenkeeper-lockfile@1
        - greenkeeper-lockfile-update
      script:
        - yarn ts:build
      after_script:
        - greenkeeper-lockfile-upload
      after_success:
        - yarn semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    - BUILD_LEADER_ID=8
